# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: w4.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='w4.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08w4.proto\"o\n\x10SampleAnnotation\x12\x14\n\x0cnon_terminal\x18\x01 \x01(\t\x12\x0f\n\x03nth\x18\x02 \x01(\x05\x42\x02\x18\x01\x12\x10\n\x08modifier\x18\x03 \x01(\t\x12\x11\n\tbegin_pos\x18\x04 \x01(\x05\x12\x0f\n\x07\x65nd_pos\x18\x05 \x01(\x05\"J\n\x0eTrainingSample\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12&\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32\x11.SampleAnnotation\"C\n\x0fTrainingSamples\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12 \n\x07samples\x18\x02 \x03(\x0b\x32\x0f.TrainingSample\"L\n\rTrainingFiles\x12\x17\n\x0f\x63onfig_filename\x18\x01 \x01(\t\x12\"\n\x1atraining_samples_filenames\x18\x02 \x03(\tb\x06proto3')
)




_SAMPLEANNOTATION = _descriptor.Descriptor(
  name='SampleAnnotation',
  full_name='SampleAnnotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='non_terminal', full_name='SampleAnnotation.non_terminal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nth', full_name='SampleAnnotation.nth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modifier', full_name='SampleAnnotation.modifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_pos', full_name='SampleAnnotation.begin_pos', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_pos', full_name='SampleAnnotation.end_pos', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=123,
)


_TRAININGSAMPLE = _descriptor.Descriptor(
  name='TrainingSample',
  full_name='TrainingSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='TrainingSample.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='TrainingSample.annotations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=199,
)


_TRAININGSAMPLES = _descriptor.Descriptor(
  name='TrainingSamples',
  full_name='TrainingSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='intent', full_name='TrainingSamples.intent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='TrainingSamples.samples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=268,
)


_TRAININGFILES = _descriptor.Descriptor(
  name='TrainingFiles',
  full_name='TrainingFiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_filename', full_name='TrainingFiles.config_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_samples_filenames', full_name='TrainingFiles.training_samples_filenames', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=346,
)

_TRAININGSAMPLE.fields_by_name['annotations'].message_type = _SAMPLEANNOTATION
_TRAININGSAMPLES.fields_by_name['samples'].message_type = _TRAININGSAMPLE
DESCRIPTOR.message_types_by_name['SampleAnnotation'] = _SAMPLEANNOTATION
DESCRIPTOR.message_types_by_name['TrainingSample'] = _TRAININGSAMPLE
DESCRIPTOR.message_types_by_name['TrainingSamples'] = _TRAININGSAMPLES
DESCRIPTOR.message_types_by_name['TrainingFiles'] = _TRAININGFILES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleAnnotation = _reflection.GeneratedProtocolMessageType('SampleAnnotation', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEANNOTATION,
  __module__ = 'w4_pb2'
  # @@protoc_insertion_point(class_scope:SampleAnnotation)
  ))
_sym_db.RegisterMessage(SampleAnnotation)

TrainingSample = _reflection.GeneratedProtocolMessageType('TrainingSample', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGSAMPLE,
  __module__ = 'w4_pb2'
  # @@protoc_insertion_point(class_scope:TrainingSample)
  ))
_sym_db.RegisterMessage(TrainingSample)

TrainingSamples = _reflection.GeneratedProtocolMessageType('TrainingSamples', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGSAMPLES,
  __module__ = 'w4_pb2'
  # @@protoc_insertion_point(class_scope:TrainingSamples)
  ))
_sym_db.RegisterMessage(TrainingSamples)

TrainingFiles = _reflection.GeneratedProtocolMessageType('TrainingFiles', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGFILES,
  __module__ = 'w4_pb2'
  # @@protoc_insertion_point(class_scope:TrainingFiles)
  ))
_sym_db.RegisterMessage(TrainingFiles)


_SAMPLEANNOTATION.fields_by_name['nth']._options = None
# @@protoc_insertion_point(module_scope)
